# Generated by Django 4.0 on 2022-01-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_pic', models.ImageField(blank=True, upload_to='customer_pics')),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('customer_email', models.CharField(max_length=200, null=True)),
                ('customer_mobile', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
