# Generated by Django 4.0 on 2022-01-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_pic', models.ImageField(blank=True, upload_to='customer_pics/')),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('customer_email', models.CharField(max_length=200, null=True)),
                ('customer_mobile', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_price', models.FloatField(null=True)),
                ('product_category', models.CharField(choices=[('service', 'Service'), ('stockable', 'Stockable')], max_length=200, null=True)),
                ('product_description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tag', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_order_referencenumber', models.CharField(max_length=200, null=True)),
                ('sale_order_quantity', models.IntegerField(null=True)),
                ('sale_order_total_price', models.FloatField(null=True)),
                ('sale_order_unit_price', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('quotation', 'Quotation'), ('ordered', 'Ordered'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('invoiced', 'Invoiced')], default='quotation', max_length=200, null=True)),
                ('sale_order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sale_order_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('sale_order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.ProductTag'),
        ),
    ]
