# Generated by Django 4.0 on 2022-01-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(blank=True, upload_to='media/customer_pics'),
        ),
    ]
