# Generated by Django 4.0 on 2022-01-24 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_saleorder_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
