# Generated by Django 4.0 on 2022-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_customer_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_price', models.FloatField(null=True)),
                ('product_category', models.CharField(choices=[('service', 'Service'), ('stockable', 'Stockable')], max_length=200, null=True)),
                ('product_description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_order_referencenumber', models.CharField(max_length=200, null=True)),
                ('sale_order_quantity', models.IntegerField(null=True)),
                ('sale_order_total_price', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('quotation', 'Quotation'), ('ordered', 'Ordered'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='quotation', max_length=200, null=True)),
                ('sale_order_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
