# Generated by Django 4.0 on 2022-01-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='sales_person',
        ),
    ]
