# Generated by Django 4.0 on 2022-01-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_producttag_product_product_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='product_tags',
            field=models.ManyToManyField(to='accounts.ProductTag'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_tag',
        ),
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.ManyToManyField(to='accounts.ProductTag'),
        ),
    ]
