# Generated by Django 4.0 on 2022-01-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_saleorder_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.ManyToManyField(blank=True, to='accounts.ProductTag'),
        ),
    ]
