# Generated by Django 4.0 on 2022-01-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_product_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(blank=True, upload_to='customer_pics/'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('ordered', 'Ordered'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('invoiced', 'Invoiced')], default='quotation', max_length=200, null=True),
        ),
    ]
