# Generated by Django 4.0 on 2022-01-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_product_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='sale_order_unit_price',
            field=models.FloatField(null=True),
        ),
    ]
